### ISSUE TITLE
Exception "The format of value 'xxx' is invalid." when api key contains character "="

### ISSUE THREAD

**Issue by BobbyWhiskey** [FusionAuth/fusionauth-netcore-client#52]
We generated a new API key and it happens to have the character "=" at the end. When i try to make an API call using the client i get this exception before the api call is even made:
```
The format of value '{my api key here}' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at io.fusionauth.DefaultRESTClient.baseRequest()
   at io.fusionauth.DefaultRESTClient.goAsync[T]()
   at io.fusionauth.FusionAuthClient.RetrieveUserAsync(Nullable`1 userId)
```

I tested the call using the generated api key using Postman and it works.

Exemple code to reproduce the error :
```
var fusionAuthClient = new FusionAuthClient("MyApiKeyHere=", fusionAuthOptions.ApiUrl, fusionAuthOptions.TenantId);
var response = fusionAuthClient.RetrieveUserAsync(Guid.Empty);
```

**Comment by mooreds** [comment]
Thanks for the bug report, @BobbyWhiskey !

Verified an API key with `=` works with curl, so it isn't a limitation of API key functionality, but rather the client library.

Temporary workaround is to use an API key without any `=` signs.
